# This config tells the robot that it is not THAT fat
move_base:
 local_costmap:
  inflation_layer:
   cost_scaling_factor: 20
   inflation_radius: 0.10
  robot_radius: 0.15
 # We need this so the robot can approach walls closer when parking
 global_costmap:
  inflation_layer:
   cost_scaling_factor: 10
   inflation_radius: 0.10
  robot_radius: 0.15
